const data = [
    {
        imgURL: "https://cdn.discordapp.com/attachments/797686485213380638/797686829922648065/unknown.png",
        summary: "The Trump administration announced Monday that 70,000 migrants were apprehended at the southwest border in November, a 64 percent increase compared to 2019 -- and a sign of a possible surge that Trump officials say could become a full-blown crisis if recent policies are ended, as promised by the incoming Biden Administration. Acting Customs and Border Protection (CBP) Commissioner Mark Morgan numbers had been creeping up since April. <strong>Morgan warned that a perceived coming shift in policy from a new incoming Biden administration was motivating others to make the journey north and that if certain Trump-era policies are ended, then border law enforcement will be unable to handle the number of migrants crossing. “</strong> If the current policies in place are revoked as critics have promised they would do...the 2,300 a day will become a full-blown crisis overnight as we stand by and watch the numbers go even higher, making last year's crisis pale in comparison, he said. During the 2019 crisis, the Trump administration accelerated its efforts to close loopholes and secure the border. Biden has promised to end numerous Trump-era immigration policies, including perhaps the most ambitious and effective of these efforts, the “Remain-in-Mexico” policy. Morgan warned that “an immigration strategy which consists of release, protect and reward is not an immigration strategy at all, it’s an open border strategy.”",
    },
    {
        imgURL: "https://cdn.discordapp.com/attachments/797686485213380638/797686884775624714/unknown.png",
        summary: "<strong>The incoming Biden administration announced on Tuesday that it would not immediately reverse restrictions imposed by President Trump that have effectively halted asylum and left thousands of migrants stranded outside the United States.</strong> The Trump administration progressively tightened restrictions on asylum, effectively sealing the border to asylum seekers by forcing them to wait in Mexico for the duration of their immigration hearings, which has left many migrants living in squalid tent encampments where kidnappings, torture and assaults at the hands of drug cartels are reportedly common. Officials said Biden aimed to pivot to what they called a more humane approach, but also that this change will happen over several months. “Migrants and asylum seekers should not at all believe the people in the region who are selling the idea that the border will suddenly be wide open to process everyone on the first day,” said Susan Rice, incoming domestic policy advisor. The Trump administration has moved in recent weeks to finalize tough border restrictions that could prove difficult for Mr. Biden to unwind. Despite Biden’s intended changes, there is no sign that his administration will refrain from enforcement, using agents backed by aerial and ground technology.",
    },
    {
        imgURL: "https://media.discordapp.net/attachments/797686485213380638/797686933001470002/unknown.png",
        summary: "President-Elect Joe Biden said this week that while he’s pushing to reverse President Donald Trump’s immigration policies, he tamped down expectations by reminding everyone this will take time. <strong>“It’s really clear to me that it is going to take a long time to fully undo the damage that the Trump administration has caused over his term”</strong> said Jonathan Jayes-Green, Vice President of Programs at The Marguerite Casey Foundation. “We’ve had four years of Stephen Miller doing everything he can to make the lives of immigrants and minorities more miserable, so we need to act urgently to transform the system into one that is more humane and actually works properly.” The Biden Administration plans to end the “Remain-in-Mexico” policy and achieve family reunification, among others, but this will take time. Trump’s harsh policies, motivated by a desire to deter migrants from coming to the border, will prove difficult for Biden to reverse quickly. Jayes-Green claims that “what we are looking for is for President-Elect Biden to use every lever at his disposal to address the harm that has been inflicted on our communities as soon as possible.”",
    },
    // {
    //     imgURL: "https://media.discordapp.net/attachments/797235184625254442/797606106032767016/Screen_Shot_2021-01-09_at_3.21.14_PM.png?width=1028&height=369",
    //     summary: "lorem ipsum asldkfjalskdjflkasjldkfj asdlfk jalskdjf asdfl alskj alsdkjf ",
    // },
];

export default data;